# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1fc44524c85a73eab56948818f1cd57692ea96dddef91005e7f78eed0f943603d120ec3ba3d7e95adb5685f64cccea52f61ff6693de70b62d7b681224274a76

test:
  secret_key_base: fcd6049e88038ab25b346856c6b08045144141787e4d9c65e820f1c8d43177afc3e4b4e3735da3c7d9960969fa2086636ae43af7aca8800f8b0ade09d0646f88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
